import lyla from "../assets/images/lyla.jpg";
import nala from "../assets/images/nala.jpg";
import panda from "../assets/images/panda.jpg";
import rocky from "../assets/images/rocky.jpg";
import tiger from "../assets/images/tiger.jpg";
import bear from "../assets/images/bear.jpg";
import daisy from "../assets/images/daisy.jpg";

export const dummyPuppies = [
  {
    id: "1",
    name: "Lyla",
    breed: "AKC French Bulldog",
    age: "3 weeks",
    image: lyla,
    isAvailable: true,
    availabilityDate: '2023-12-15',
    health: 'Good',
    shots: ['Rabies', 'Distemper'],
    microchipped: true,
    additionalNotes: 'Friendly and playful',
  },
  {
    id: "2",
    name: "Nala",
    breed: "AKC French Bulldog",
    age: "3 weeks",
    image: nala,
    isAvailable: true,
    availabilityDate: '2023-12-15',
    health: 'Good',
    shots: ['Rabies', 'Distemper'],
    microchipped: true,
    additionalNotes: 'Friendly and playful',
  },
  {
    id: "3",
    name: "Panda",
    breed: "AKC French Bulldog",
    age: "3 weeks",
    image: panda,
    isAvailable: true,
    availabilityDate: '2023-12-15',
    health: 'Good',
    shots: ['Rabies', 'Distemper'],
    microchipped: true,
    additionalNotes: 'Friendly and playful'
  },
  {
    id: "4",
    name: "Rocky",
    breed: "AKC French Bulldog",
    age: "4 weeks",
    image: rocky,
    isAvailable: true,
    availabilityDate: '2025-09-15',
    health: 'Good',
    shots: ['Rabies', 'Distemper'],
    microchipped: true,
    additionalNotes: 'Friendly and playful',
  },
  {
    id: "5",
    name: "Tiger",
    breed: "AKC French Bulldog",
    age: "3 weeks",
    image: tiger,
    isAvailable: true,
    availabilityDate: '2025-09-15',
    health: 'Good',
    shots: ['Rabies', 'Distemper'],
    microchipped: true,
    additionalNotes: 'Friendly and playful',
  },
  {
    id: "6",
    name: "Bear",
    breed: "AKC French Bulldog",
    age: "3 weeks",
    image: bear,
    isAvailable: true,
    availabilityDate: '2025-09-15',
    health: 'Good',
    shots: ['Rabies', 'Distemper'],
    microchipped: true,
    additionalNotes: 'Friendly and playful',
  },
  {
    id: "7",
    name: "Daisy",
    breed: "AKC French Bulldog",
    age: "3 weeks",
    image: daisy,
    isAvailable: true,
    availabilityDate: '2025-09-15',
    health: 'Good',
    shots: ['Rabies', 'Distemper'],
    microchipped: true,
    additionalNotes: 'Friendly and playful',
  },
];
